[[custom_groups]]
name = "â™»ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [".*",
"[]DIRECT"]

#[[custom_groups]]
#name = "ğŸŒ ä¼˜å…ˆç›´è¿"
#type = "select"
#rule = ["[]DIRECT",
#"â™»ï¸ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸŒ è‡ªå®šä¹‰ç›´è¿"
type = "select"
rule = ["[]DIRECT",
"â™»ï¸ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸŒ è‡ªå®šä¹‰ä»£ç†"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ è‡ªå®šä¹‰æ‹¦æˆª"
type = "select"
rule = ["[]REJECT",
"[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ UltraMobile"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ VPSJP"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ VPSKR"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ” Google"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ” Bing"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ” Yahoo"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ—º Speedtest"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ§² OpenAI"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ“² èŠå¤©è½¯ä»¶"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ™ Discord"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ Instagram"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ YouTube"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ Netflix"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ DisneyPlus"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

#[[custom_groups]]
#name = "ğŸ¬ HBOGO"
#type = "select"
#rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
#"[]DIRECT",
#".*"]

[[custom_groups]]
name = "ğŸ¬ AppleTV+"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ PrimeVideo"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ HBOMAX"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ é¦™æ¸¯åª’ä½“V"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ å°æ¹¾åª’ä½“"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ æ—¥æœ¬åª’ä½“"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ éŸ©å›½åª’ä½“"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ Bç«™æ¸¯æ¾³å°"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ Bç«™ä¸œå—äºš"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ EMBY"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ¬ çˆ±å¥‡è‰º"
type = "select"
rule = ["[]DIRECT",
"[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸ¬ XPTV"
type = "select"
rule = ["[]DIRECT",
"[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸ¶ TikTok"
type = "select"
rule = ["[]DIRECT",
"[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸµ Spotify"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸµ AppleMusic"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸµ å…¶ä»–å›½å¤–éŸ³ä¹"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–æµåª’ä½“"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ å›½å†…æµåª’ä½“"
type = "select"
rule = ["[]DIRECT",
"[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸ”– OneDrive"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "â˜ï¸ iCloud"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ§© å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

#[[custom_groups]]
#name = "ğŸ® æ¸¸æˆå¹³å°"
#type = "select"
#rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
#"[]DIRECT",
#".*"]

#[[custom_groups]]
#name = "ğŸ® æ¸¸æˆä¸‹è½½"
#type = "select"
#rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
#"[]DIRECT",
#".*"]

[[custom_groups]]
name = "ğŸ“ª é‚®ä»¶æœåŠ¡"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

#[[custom_groups]]
#name = "ğŸ¯ P2Pä¸‹è½½"
#type = "select"
#rule = ["[]DIRECT",
#"[]REJECT"]

#[[custom_groups]]
#name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
#type = "select"
#rule = ["[]REJECT",
#"[]DIRECT"]

[[custom_groups]]
name = "ğŸŒ å…¨çƒä»£ç†"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]

[[custom_groups]]
name = "ğŸŒ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT",
"â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
".*"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]â™»ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]DIRECT",
".*"]