#[[rulesets]]
#group = "ğŸŒ ä¼˜å…ˆç›´è¿"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MaYingRules/PriorityDirect.list"

[[rulesets]]
group = "ğŸŒ è‡ªå®šä¹‰ç›´è¿"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/MyDirect.list"

[[rulesets]]
group = "ğŸŒ è‡ªå®šä¹‰ä»£ç†"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/MyProxy.list"

[[rulesets]]
group = "ğŸŒ è‡ªå®šä¹‰æ‹¦æˆª"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/MyReject.list"

[[rulesets]]
group = "ğŸŒ UltraMobile"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/UltraMobile.list"

[[rulesets]]
group = "ğŸŒ VPSJP"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/VPSJP.list"

[[rulesets]]
group = "ğŸŒ VPSKR"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/VPSKR.list"

[[rulesets]]
group = "ğŸ” Google"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Google.list"

[[rulesets]]
group = "ğŸ” Bing"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Bing.list"

[[rulesets]]
group = "ğŸ” Yahoo"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Yahoo.list"

[[rulesets]]
group = "ğŸ—º Speedtest"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Speedtest.list"

[[rulesets]]
group = "ğŸ§² OpenAI"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/OpenAI.list"

[[rulesets]]
group = "ğŸ“² èŠå¤©è½¯ä»¶"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/ChatSoftware.list"

[[rulesets]]
group = "ğŸ™ Discord"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Discord.list"

[[rulesets]]
group = "ğŸ¬ Instagram"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Instagram.list"

[[rulesets]]
group = "ğŸ¬ YouTube"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/YouTube.list"

[[rulesets]]
group = "ğŸ¬ Netflix"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Netflix.list"

[[rulesets]]
group = "ğŸ¬ DisneyPlus"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/DisneyPlus.list"

#[[rulesets]]
#group = "ğŸ¬ HBOGO"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/HBOGO.list"

[[rulesets]]
group = "ğŸ¬ AppleTV+"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/AppleTV%2B.list"

[[rulesets]]
group = "ğŸ¬ PrimeVideo"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/PrimeVideo.list"

[[rulesets]]
group = "ğŸ¬ HBOMAX"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/HBOMAX.list"

[[rulesets]]
group = "ğŸ¬ é¦™æ¸¯åª’ä½“"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/HongKongMedia.list"

[[rulesets]]
group = "ğŸ¬ å°æ¹¾åª’ä½“"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/TaiwanMedia.list"

[[rulesets]]
group = "ğŸ¬ æ—¥æœ¬åª’ä½“"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/JapaneseMedia.list"

[[rulesets]]
group = "ğŸ¬ éŸ©å›½åª’ä½“"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/KoreanMedia.list"

[[rulesets]]
group = "ğŸ¬ Bç«™æ¸¯æ¾³å°"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/BilibiliHKTW.list"

[[rulesets]]
group = "ğŸ¬ Bç«™ä¸œå—äºš"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/BilibiliSoutheastAsia.list"

[[rulesets]]
group = "ğŸ¬ EMBY"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/EMBY.list"

[[rulesets]]
group = "ğŸ¬ çˆ±å¥‡è‰º"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/iQIYI.list"

[[rulesets]]
group = "ğŸ¬ XPTV"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/XPTV.list"

[[rulesets]]
group = "ğŸ¶ TikTok"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/TikTok.list"

[[rulesets]]
group = "ğŸµ Spotify"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/Spotify.list"

[[rulesets]]
group = "ğŸµ AppleMusic"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/AppleMusic.list"

[[rulesets]]
group = "ğŸµ å…¶ä»–å›½å¤–éŸ³ä¹"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MyRules/OtherForeignMusic.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–æµåª’ä½“"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/ForeignStreamingMedia.list"

#[[rulesets]]
#group = "ğŸŒ å›½å†…æµåª’ä½“"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/DomesticStreamingMedia.list"

[[rulesets]]
group = "ğŸ”– OneDrive"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/OneDrive.list"

[[rulesets]]
group = "â˜ï¸ iCloud"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/iCloud.list"

[[rulesets]]
group = "ğŸ§© å¾®è½¯æœåŠ¡"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/MicrosoftServices.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/AppleServices.list"

#[[rulesets]]
#group = "ğŸ® æ¸¸æˆå¹³å°"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/GamePlatform.list"

#[[rulesets]]
#group = "ğŸ® æ¸¸æˆä¸‹è½½"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/GameDownload.list"

[[rulesets]]
group = "ğŸ“ª é‚®ä»¶æœåŠ¡"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/MailServices.list"

#[[rulesets]]
#group = "ğŸ¯ P2Pä¸‹è½½"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/TAGRules/P2PDownload.list"

#[[rulesets]]
#group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
#ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MaYingRules/AdReject.list"

[[rulesets]]
group = "ğŸŒ å…¨çƒä»£ç†"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MaYingRules/GlobaProxy.list"

[[rulesets]]
group = "ğŸŒ å…¨çƒç›´è¿"
ruleset = "https://ghp.ci/https://raw.githubusercontent.com/JackKingKong/sub/main/CustomRules/MaYingRules/GlobaDirect.list"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
